[package]
name = "loan_canister"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
candid = "0.9"
ic-cdk = "0.11"
ic-cdk-macros = "0.8"
